### ISSUE TITLE
Error: Cannot find module 'escape-string-regexp' when using this package

### ISSUE THREAD

**Issue by robkorv** [robkorv/postcss-selector-prefix#56]
I think this needs to be in the peerDependencies?

**Comment by robkorv** [comment]
Different plan. Going to use https://github.com/tc39/proposal-regex-escaping/blob/3d45b23af8e8824dd689deb35856a80fa52d78ca/polyfill.js to fix the build error when using `require("escape-string-regexp")`

```
# /home/runner/work/postcss-selector-prefix/postcss-selector-prefix/index.js:4
# const escapeStringRegexp = require("escape-string-regexp");
#                            ^
# Error [ERR_REQUIRE_ESM]: require() of ES Module /home/runner/work/postcss-selector-prefix/postcss-selector-prefix/node_modules/escape-string-regexp/index.js from /home/runner/work/postcss-selector-prefix/postcss-selector-prefix/index.js not supported.
# Instead change the require of /home/runner/work/postcss-selector-prefix/postcss-selector-prefix/node_modules/escape-string-regexp/index.js in /home/runner/work/postcss-selector-prefix/postcss-selector-prefix/index.js to a dynamic import() which is available in all CommonJS modules.
#     at Object.<anonymous> (/home/runner/work/postcss-selector-prefix/postcss-selector-prefix/index.js:4:28)
#     at Object.<anonymous> (/home/runner/work/postcss-selector-prefix/postcss-selector-prefix/index.test.js:5:16) {
#   code: 'ERR_REQUIRE_ESM'
# }
```
